apiVersion: v1
kind: Service
metadata:
  name: wireguard-service-milan
  namespace: liqo-demo
spec:
  selector:
    app: gateway-wg-milan
  ports:
    - protocol: UDP
      port: 51820
      targetPort: 51820
      nodePort: 30001 # Cambiare rispetto al servizio di Roma per evitare conflitti
  type: NodePort

