apiVersion: v1
kind: Service
metadata:
  name: gateway-milan-service
  namespace: liqo-tenant-europe-cloud
spec:
  selector:
    app: gateway-wg-milan
  ports:
    - protocol: UDP
      port: 51820
      targetPort: 51820
      nodePort: 30001 # Cambiare rispetto al servizio di Roma per evitare conflitti
  type: NodePort

