apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-config-milan
  namespace: liqo-demo
data:
  wg0.conf: |
    [Interface]
    PrivateKey = WMQEV0no7aqmLnADP++qBGE3ekBPnUY39W+Clpl9Tkk=
    Address = 10.204.1.2/24
    ListenPort = 51820

    [Peer]
    PublicKey = NMUiSPeIFJkIZsHBU1cqO2s4r9HHnd/bWH3mubg19xs=
    Endpoint = 172.18.0.3:30000
    AllowedIPs = 10.204.1.0/24, 10.201.0.0/24
    PersistentKeepalive = 25

