apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: allow-impersonation
rules:
  - apiGroups: [""]
    resources: ["users"]
    verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: europe-cloud-impersonation
subjects:
  - kind: User
    name: europe-cloud  # Utente che sta cercando di impersonare
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: allow-impersonation
  apiGroup: rbac.authorization.k8s.io
