apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-role-binding
  namespace: liqo-demo  # Namespace dove esegui il DaemonSet
subjects:
  - kind: ServiceAccount
    name: default  # O il nome del tuo ServiceAccount
    namespace: liqo-demo
roleRef:
  kind: Role
  name: role-daemon
  apiGroup: rbac.authorization.k8s.io

