apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-config-rome
  namespace: liqo-demo
data:
  wg0.conf: |
    [Interface]
    PrivateKey = iIMvZeUSoUTMaIL9JrQlVtvbJBcD25ETYU2JALZPNms=
    Address = 10.204.1.1/24
    ListenPort = 51820

    [Peer]
    PublicKey = Nzx7NYrcEpu4irury91Ki9HmjSFV5dzJNd4KDpH2OzE=
    Endpoint = 172.18.0.4:30001
    AllowedIPs = 0.0.0.0/0
    PersistentKeepalive = 25

