apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: liqo-network-binding
subjects:
  - kind: User
    name: europe-cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: liqo-network-viewer
  apiGroup: rbac.authorization.k8s.io

