apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: liqo-network-viewer
  namespace: liqo
rules:
  - apiGroups: ["networking.liqo.io"]
    resources: ["connections"]
    verbs: ["get", "list"]

