apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: liqo-network-binding
  namespace: liqo
subjects:
  - kind: User
    name: europe-cloud
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: liqo-network-viewer
  apiGroup: rbac.authorization.k8s.io

