apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: europe-cloud-read-configmaps
subjects:
  - kind: User
    name: europe-cloud  # Assicurati che corrisponda al nome dell'utente che hai verificato
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view  # Il ruolo "view" ha i permessi di lettura su ConfigMaps
  apiGroup: rbac.authorization.k8s.io
